Mozza\Core\Entity\User:
    type: entity
    table: ~
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

        email:
            type: string
            length: 255
            nullable: false

        password:
            type: string
            length: 255
            nullable: false

        salt:
            type: string
            length: 255
            nullable: false

        roles:
            type: json_array        

    lifecycleCallbacks: {  }