Mozza\Core\Entity\SystemStatus:
    type: entity
    table: ~
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

        postcachelastupdate:
            type: datetime
            nullable: true

        configuredversion:
            type: string
            length: 32
            nullable: false

        initialized:
            type: boolean
            nullable: false

    lifecycleCallbacks: {  }
